### PR TITLE
Feature/atomic functions

### PR DESCRIPTION
**Pull request by dschaper**
Misc code formatting cleanup and a few thematic changes to fit output on one line.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
So is #94 separate from this?  It looks similar.

**Comment by dschaper** [comment]
#94 Is separate, it has a fix for the merge conflicts that was preventing the stuff from yesterday that was merged into the development branch from merging to master. This PR has some other feature updates, if you merge #94 then a lot of the commits listed here should be cleared.

**Comment by jacobsalmela** [comment]
OK.  I plan to merge it today--I just want to do a bit more testing on my end.  Most of the comments I get are that the Pi-hole is very stable and I want to keep it that way.  Thanks for all this hard work!!

**Comment by dschaper** [comment]
No problem, that's why I'm trying to break stuff out to bug branches or feature branches. What's the best way for you, to PR to development?

**Comment by dschaper** [comment]
And now I'm seeing some problems with Maha, it returns different lists with each curl. Sometimes a small list, sometimes a huge list, sometimes no list at all. All with the same curl...?

**Comment by jacobsalmela** [comment]
Yeah, for big changes PRs to the development branch is best.  If it's just small stuff that I can look at quickly, PRs to master is better for a faster merge.

**Comment by jacobsalmela** [comment]
The mahakala list is a weird one...it needs to have be referred from that certain URL.  It's really called the Mother of All Ad Blocks:

http://forum.xda-developers.com/showthread.php?t=1916098

**Comment by dschaper** [comment]
Apparently that's not all it blocks! ;)
\

**Comment by dschaper** [comment]
I found another list, http://www.malwaredomains.com/ but I'm not sure if you just want to target ads, or would confirmed malware spouts be part of what you'd like to add? (They don't have a hosts format, so there would be some massaging the list to get it to PiHole format.)

**Comment by jacobsalmela** [comment]
Is that different than the [malwaredomains that is already in the list](https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh#L22)?

I also have noticed inconsistent numbers with the mahakala list, which is weird.

**Comment by dschaper** [comment]
Oh, it's the same, nevermind!

**Comment by jacobsalmela** [comment]
OK, so this PR looks like it is mostly some formatting and then the `piholeIP` change, yes?

**Comment by dschaper** [comment]
Yeah, and I moved the blacklisting from Scwartz to pulsar, to keep each function doing only one thing. Pulsar now just handles black and white listing (hence pulsar) and Schwartz only collapses all the individual files into a single list.

**Comment by jacobsalmela** [comment]
OK, cool.  Thanks!  It looks good.

**Pull request merged**
