### PR TITLE
Update gravity-adv.sh

### PR DESCRIPTION
**Pull request by dwin999**
This works much faster.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Could you explain--in detail--how your code works?  It is definitely faster, but I want to understand how it works.  Explain what each piece of code does.  Thanks

**Comment by dwin999** [comment]
catting a file to stdin is much faster than looping over a file in bash. 

cat /tmp/matter.txt | sort | uniq | sed '/^$/d' |  I just copied your code.
awk -v "IP=$piholeIP" '{sub(/\r$/,""); print "address=/"$0"/"IP}' just formats the code to the dnsmasq format, removing any \r using awk regex.

**Comment by jacobsalmela** [comment]
I'm just not too familiar with all of the awk stuff.  I have really only used the most basic to print a column.

**Review by saltman007web — COMMENTED** [review]
commit

**Review by saltman007web — COMMENTED** [review]
2

**Pull request merged**
