### PR TITLE
Fix chronometer

### LINKED ISSUE #200: LCD Data & Web Interface Show Different Domain Numbers
My LCD domain numbers do not match what shows in the web interface by 60K.

LCD Domains: 130K
Web Interface Domains: 65K

### PR DESCRIPTION
**Pull request by PromoFaux**
see #201 for details

fixes #200

### CODE REVIEW

**Comment by PromoFaux** [comment]
More of a bug fix than an enhancement, but you're the boss :)

**Comment by jacobsalmela** [comment]
Yeah, there's not a bug "fix" label though!

**Comment by PromoFaux** [comment]
[here you go](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/) :)

**Comment by jacobsalmela** [comment]
Nice.  I thought there was somewhere to do that but I just couldn't find it.

**Comment by dschaper** [comment]
I can't test this yet, but I'll drop it in a new bugfix branch to test. Give me a few minutes...

**Comment by dschaper** [comment]
Okay, there is a new branch `bugfix/Chronometer` ready for alpha testing.

**Pull request merged**
