### PR TITLE
Use last IP for selected interface

### PR DESCRIPTION
**Pull request by dschaper**
Fixes bug #112 . Pulls the last IP for selected interface which should be the IP for the interface if the user added a custom IP in the basic install. Interface can have multiple IP's without issues.

### CODE REVIEW

**Comment by dschaper** [comment]
Fix bug #113

**Comment by jacobsalmela** [comment]
I'm so bad with conflicts...I can never figure them out.  Any ideas?

**Comment by dschaper** [comment]
Heh, yeah, let me see what I can figure out...

**Comment by dschaper** [comment]
Try the merge to development, and we'll try to merge in piece by piece and close out what we don't need.

**Pull request closed without merging**
