### PR TITLE
Bugfix for Chronometer

### LINKED ISSUE #200: LCD Data & Web Interface Show Different Domain Numbers
My LCD domain numbers do not match what shows in the web interface by 60K.

LCD Domains: 130K
Web Interface Domains: 65K

### PR DESCRIPTION
**Pull request by dschaper**
Fixes #200 
Move call to CheckIPv6 function into CalcBlockedDomains, rather than relying on remembering to call it before you call CalcBlockedDomains. @PromoFaux  submission

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Looks good!  I think I have a bunch of old branches that I can probably get rid of...  I'll have to go through those.

**Comment by dschaper** [comment]
Now are you all seeing the beauty of branches? (Branch early and often, and it keeps down the merge conflicts and lets you test atomic code...) The only down side is you have to do a lot of the merging from CLI, GitHub doesn't quite have the capabilities to do it yet. (Or I just don't know how to use GitHub  to do it, lol...)

**Comment by jacobsalmela** [comment]
Maybe it warrants a little section on the README or the wiki for people who want to submit PRs.

**Comment by dschaper** [comment]
It could, just a note for users to submit to Development. By doing it via CLI you can pull their branches into any branch you want, not just the branch that the PR is targeting. Right now with so many different fixes and features working at the same time I'm splitting them to their own branches to test the specific issue and then to master or development depending on if it needs further testing. But when things go a little more quiescent it would be easier if they PR'd to development...

**Pull request merged**
