### PR TITLE
FHS Location Changes

### PR DESCRIPTION
**Pull request by dschaper**
Per Debian Maintainer's Guide:
"Most third-party software installs itself in the /usr/local directory hierarchy. On Debian this is reserved for private use by the system administrator, so packages must not use directories such as /usr/local/bin but should instead use system directories such as /usr/bin, obeying the Filesystem Hierarchy Standard (FHS)."

https://www.debian.org/doc/manuals/maint-guide/modify.en.html

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Interesting.  I'll have to read more into that.  Also, I will have to update a lot of my documentation on pi-hole.net when this pull is merged.

**Comment by dschaper** [comment]
Yeah, it's under section 3.3. It's kind of a different take than what I assumed to be cannon.

**Comment by jacobsalmela** [comment]
Same here.  Good to keep learning though!

**Comment by dschaper** [comment]
Do you still use TOIlet or bc? I didn't see where they were still needed?

**Comment by jacobsalmela** [comment]
Yes, it is used with `chronometer.sh`, the real-time mini LCD display script.  There is probably a small subset of people actually using it, but it's nice to have anyway.

**Comment by jacobsalmela** [comment]
I think I will merge #85 before this as the file path change will take me a lot longer to update all of my documentation.  Plus, having the functions will be easier to work with in the future.

**Comment by jacobsalmela** [comment]
Following the links through the one you provided, it points to [here](https://www.debian.org/doc/packaging-manuals/fhs/fhs-2.3.html#USRBINMOSTUSERCOMMANDS), which reads:

_The /usr/local hierarchy is for use by the system administrator when installing software locally. It needs to be safe from being overwritten when the system software is updated. It may be used for programs and data that are shareable amongst a group of hosts, but not found in /usr._

That makes me feel like it is in the right place as-is.

**Comment by dschaper** [comment]
It's kind of a catch-22, as pointed out here http://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux /usr/bin would be for the packaged version, while /usr/local/bin would be for the version that is pulled directly. The packaged version would need to go in /usr/bin per the Debian Policy. Not sure how to handle this one.

**Comment by dschaper** [comment]
9.1.2 Site-specific programs

As mandated by the FHS, packages must not place any files in /usr/local, either by putting them in the file system archive to be unpacked by dpkg or by manipulating them in their maintainer scripts.

**Comment by jacobsalmela** [comment]
Hmm, yeah that's weird.  So once we get the `apt-get` version going, that would go into `/usr/bin` but since user's are just downloading the files and adding them manually (semi-automatically using the automated installer), they can stay in `/usr/local/bin`?

**Comment by dschaper** [comment]
That's pretty much what I get from the documentation. The packaging would take care of moving to `/usr/bin`. I don't know how that would affect the documentation though, having two different install locations. I think you can probably close this one out and leave things as is while I'm sorting out the packaging.

**Comment by jacobsalmela** [comment]
Sounds good.  The documentation part will be a challenge since I have so many posts out there on it, but that will be my own fun endeavor to undertake.  =)

**Comment by dschaper** [comment]
Ah, the fun of documentation! I've never used GitHub's Wiki, maybe that would be a way to get some help, write up a framework in the Wiki and get the end users to fill the details.

**Comment by jacobsalmela** [comment]
That's probably a good idea.  I added the Wiki when making the project for that purpose, but I made most of the posts on my blog and pi-hole.net.  It might be a good place to centralize the documentation for people.

**Pull request closed without merging**
