### PR TITLE
Switched CRLF to LF (DOS to UNIX)

### LINKED ISSUE #181: blacklist.sh has erroneous CRLF items, causing it to malfunction
Hi guys,

Thanks for the awesome fixes on the whitelist/blacklist stuff! It fixed my problem that I was having. :)

blacklist.sh looks like it has some troubles though - it's got CRLF items in the line breaks, which is causing problems executing the script. A "cat -v whitelist.sh" and "cat -v blacklist.sh" will show the differences - whitelist.sh doesn't  have any of the "^M" items, blacklist.sh does. Taking those out with vi seemed to get blacklist.sh working again for me.

### PR DESCRIPTION
**Pull request by PromoFaux**
Fixes #181

### CODE REVIEW

**Comment by PromoFaux** [comment]
@jacobsalmela Sorry for all the closed pull requests! I'll get my head around this soon.... Think my fork needs tidying, will probably delete it and start again after this is pushed....

**Comment by jacobsalmela** [comment]
It's OK.  I still don't really understand it all myself.  I have been meaning to watch the Lynda training videos.

I'm not seeing any differences in the script, however.

**Comment by PromoFaux** [comment]
It's what you can't see that's changed! if you compare this version of blacklist.sh to the one in the master (using cat -V ) You'll see that the <code>^M<code> at the end of the lines have gone.

**Comment by PromoFaux** [comment]
image

@jacobsalmela see the line ending differences in the above screenshot

**Comment by jacobsalmela** [comment]
ahh OK.  I'll try that.  I wonder if you can see it via `od` as well, which can also be used to [show hidden characters](http://jacobsalmela.com/octal-dump-od-shows-you-hidden-characters-and-ascii-values/).

**Comment by PromoFaux** [comment]
Do you need me to submit a pull into master?

**Comment by jacobsalmela** [comment]
Yeah, that would be good.  I didn't realize it was in a different branch.  I always forget to check that.

**Comment by Mcat12** [comment]
You could just merge whitelist into master.

**Pull request merged**
