### PR TITLE
Add GPL V2+ headers to script files

### PR DESCRIPTION
**Pull request by dschaper**
More documentation/copyright...

### CODE REVIEW

**Comment by jacobsalmela** [comment]
It all looks good, but what is the `gravity.pod`?  Some sort of `man` page?

**Comment by dschaper** [comment]
Forgot that I left that in there. Yes, it's the POD markup page that gets converted by `pod2man.pl`. It should be in the debian branch, I'll clear that out before the merge. (Last final is tonight so I'll get it either later tonight after the final or tomorrow morning, depends on how much coffee I down before the exams...)

**Comment by jacobsalmela** [comment]
OK, so do you want me to hold off on this merge until I get your go-ahead?

**Comment by dschaper** [comment]
Go ahead, it was just a quick `git rm` to pull out the file, should be okay to merge.

**Pull request merged**
