### PR TITLE
Refactored gravity.sh

### PR DESCRIPTION
**Pull request by dschaper**
Gravity.sh with refactored code.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Haha, this is my favorite PR.  I love that you went the extra mile to fit the theme; your schwarzschild function made me laugh.

I will do some testing to verify everything before merging.

**Comment by jacobsalmela** [comment]
This seems to run a lot faster now.  Even on my B+.  I just have a few more tests to run.

**Comment by dschaper** [comment]
Good, fix for the persistent domain (maha) in #86 should help with resolving #89.

**Comment by dschaper** [comment]
Can you tag a new release for this and create a tarball? It would help on setting a base for the packaging. Debian is kind of harsh on their requirements. (The linter throws a notification that it doesn't like having .sh because it's possible the scripting language may change in the future and the extension would be invalid?!)

**Pull request merged**
