### PR TITLE
Sub space transport fix

### PR DESCRIPTION
**Pull request by miketedesco**
This bit me so I wanted to fix it.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
Sorry about that.  However, if you simply check if `/etc/pihole` is there, it doesn't mean it is the original Pi-hole.  The `adList.conf` was really the only unique file that does not exist in the new version.  

So your code would run every time for current users.

**Comment by miketedesco** [comment]
I just started using this app a month ago.  As I was looking around here it seemed that you it was redesigned.   Can you give me a list of files for the new version you would like to back up?  I will fix it right up if that cool with you.

**Comment by jacobsalmela** [comment]
The function you are editing already backs up all the necessary files.  Likely, there won't be many users who want or need these files.  I thought of even abandoning the function all together since the 2.0 is so much better.

**Comment by miketedesco** [comment]
Cool

**Pull request closed without merging**
