### PR TITLE
fixes corrupt lines that have two dots

### PR DESCRIPTION
**Pull request by CHannema**
some of the downloaded files have domains entries like 'ads..com'. These are invalid and should be removed.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
So this works well, but I would like to see some way to integrate it into an earlier part of the script.  I recently updated my lists and they were are 1.6 million entries, so your command has to parse through the entire file a second time.  I would like to minimize that if possible.

I was thinking it could be integrated into [line 58](https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh#L58).

**Comment by CHannema** [comment]
You make a valid point, so I've moved the sed command earlier in the file.
This should work for both existing installations and new ones.
Seemed better/more efficient placing it past [line 68](https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh#L65).

**Comment by korhadris** [comment]
Two comments:

1. I don't know if it happens, but I'd want to handle the case of two or more '.' characters in your sed expression:
 `sed 's/\.\.\+/./g'`
(I also removed the extra escape of `.` in the replacement portion of your regexp, as it isn't needed in by sed.)

2. I would think you can add your sed as part of line 71; pipe the output of awk through sed before redirecting to the file:
`echo "$data" | awk 'NF {if ($1 !~ "#") { if (NF>1) {print $2} else {print $1}}}' |  sed 's/\.\.\+/./g' > $saveLocation."$justDomainsExtension"`

**Comment by korhadris** [comment]
I expect this should fix the primary concern in #32. There is some additional discussion in #32 (some more regexps) that could be applied if there are concerns with leading or trailing `.` characters as well.

**Comment by korhadris** [comment]
As I was fixing other parts of #32 and #35 today, I included this part as one of my sed expressions.

**Comment by CHannema** [comment]
Alright, then I guess this one can be closed?
I see the suggested solution has already been improved upon elsewhere. ( I hadn't checked the actual issues page, whoops).
Let me know if there's anything else, otherwise I'll close this one in a few days.

**Comment by jacobsalmela** [comment]
This should be fixed via #38

**Pull request closed without merging**
