### PR TITLE
Use pre-defined variables for chooseInterface()

### LINKED ISSUE #160: Interfaces
Hi guys,
Just love this idea. But I have a question, can i got this server on a wireless, because each time I choose wlan0 it's saying that I've chosen eth0. So it's a bug ? 
Thank you

### PR DESCRIPTION
**Pull request by dschaper**
Fixed #160. Use globally defined variables in `chooseInterface()`.

### CODE REVIEW

**Comment by jacobsalmela** [comment]
I tried it with just a single interface and got this:

```
Using interface: eth0
IPv4 selected.
IPv6 selected.
Using IPv4
Your static IPv4 address:    192.168.1.100/24
Your static IPv4 gateway:    192.168.1.1
Cannot find device "192.168.1.100/24"
Setting IP to 192.168.1.100/24.  You may need to restart after the install is complete.
Using IPv6.
```

**Comment by dschaper** [comment]
I pushed the wrong version. Will fix and open a new PR.

**Comment by dschaper** [comment]
I'm taking a closer look at this one. A shakedown brought up a few more tweaks that I need to look at.

**Comment by PromoFaux** [comment]
@dschaper @jacobsalmela Was this ever resolved? Got a user on [reddit](https://www.reddit.com/r/pihole/comments/47pwpj/cant_install/) who can't seem to select `wlan0`

**Pull request closed without merging**
