### PR TITLE
Hotfixes for install.sh

### PR DESCRIPTION
**Pull request by PromoFaux**
I'll keep committing to this as I go along, not meant for merging just yet, more so you know where I'm at with changes. Will ping @jacobsalmela or @dschaper when it's ready to be merged to dev

see #211

### CODE REVIEW

**Comment by PromoFaux** [comment]
There's a couple other things that could do with tidying up in the script I noticed, hence request to not merge just yet

**Comment by PromoFaux** [comment]
@jacobsalmela @dschaper This is now ready for review and testing in the dev/alpha branch. 

* Fixes issues with the ownership of files in `/etc/pihole` as we discussed earlier in #191 
* Cleans up the output of the script to make it easier to understand what is going on.
* Tidied up the logic for deciding if IPv4 or IPv6 or both or none had been selected.
* Checks for existing installation and either removes or preserves files depending on what they are. (e.g `whitelist.txt` and `blacklist.txt`. 
* Also preserves `/var/www/html/pihole/index.html' if it exists, as users may have customised that.

**Comment by dschaper** [comment]
Meant to alpha branch it, but it looks good. Like the spinner...

**Comment by PromoFaux** [comment]
> Like the spinner...

Borrowed code snippets are fun.

**Comment by jacobsalmela** [comment]
@dschaper, just wanted to touch base on the development branch.  I'm still looking over everything from today and plan on trying some of the changes out tonight.

**Comment by dschaper** [comment]
@jacobsalmela I can revert the latest change and send it to an alpha branch if you'd like.

**Comment by jacobsalmela** [comment]
No need.  I'm just getting caught up.

**Comment by dschaper** [comment]
Okay, today was a bit quieter than yesterday, heh...

**Comment by jacobsalmela** [comment]
I try to watch the activity throughout the day, but it's not always possible.  Then I get home and try to catch up!

**Comment by PromoFaux** [comment]
Looks like theres been a [fair bit of talk about it](https://www.reddit.com/r/pihole/search?q=pi-hole&sort=new&t=all) on reddit in the past week or so. It's certainly how I found out about it!

**Comment by jacobsalmela** [comment]
Whoa.  An entire subreddit devoted to Pi-hole.  That's weird; I never thought the project would gain this much attention!

I really wish I could do this full time.  The donation-based model doesn't net much and is very inconsistent.

**Comment by dschaper** [comment]
Can someone that has a reddit account let them know about the GitHub Repo? It would be easier to track issues in one place... (I've even been thinking about setting up a trouble-ticket package, but I'm looking for one that integrates with GitHub Issues...)

**Comment by jacobsalmela** [comment]
Yeah, that would certainly help to point people here so they aren't trying to figure stuff out on their own.

**Comment by dschaper** [comment]
https://freshdesk.com/pricing looks like it may work...

**Comment by PromoFaux** [comment]
I'll get in touch with the moderator of the subreddit tomorrow, and get him to make a stickied thread.

**Comment by jacobsalmela** [comment]
Cool, thanks @PromoFaux.

@dschaper.  Three agents for free is not too bad.  Probably a little more professional then my slow-to-update FAQs on pi-hole.net.

**Comment by dschaper** [comment]
Lol, I'll see how to set it up, it says they integrated with GitHub Issues...

**Comment by PromoFaux** [comment]
I've started [a thread](https://redd.it/41z9ji) over on reddit and messaged the mods to request it gets  stickied!

**Comment by jacobsalmela** [comment]
Nice, thanks man!

**Comment by PromoFaux** [comment]
I've also been looking into GitHub organisations. For example, the source could be stored in github.com/pi-hole, and then you're free to fork off of it and make many branches without cluttering up the base line. Have sent you an invite, and I'll admin you so you can look into it and play about. Might even be worth setting up a [slack](https://slack.com) channel for dev chat without cluttering up the issues and PR with chat..

**Comment by dschaper** [comment]
Is there a way for the current repo to be brought into an organization? We don't want to lose the current stars and conversations. Maybe @jacobsalmela could create a new organization and bring the repo into that org? (I have an organization for my consulting company and I can transfer my repo's into the org but only to org's that I own...)

**Comment by dschaper** [comment]
I've never heard of Slack, I'll take a look... Is it like a private IRC setup?

**Comment by jacobsalmela** [comment]
@PromoFaux, can you delete the organization and I will re-create it to transfer the stars and conversations over?

I also made pihole.slack.com

**Comment by PromoFaux** [comment]
I've deleted the organisation i created called 'pi-hole' from playing about earlier, so that's free to use again!

And yeah, from what I've been reading you can transfer a repo to the organisation. Obvisouly if we do that, we'll have to update all the github references in the scripts to point to the right repo :)

**Comment by jacobsalmela** [comment]
I'll explore around and see what would happen.

**Comment by PromoFaux** [comment]
>I also made pihole.slack.com

Could you send an invite over to `promofaux@rner.email`, please?

**Comment by dschaper** [comment]
You guys are quick!!

**Pull request merged**
