### PR TITLE
Possible fix for gravity.sh whitelisting

### PR DESCRIPTION
**Pull request by PromoFaux**
Just something that was bugging me, whitelist.sh was failing on the last line due to incorrect permissions.

### CODE REVIEW

**Comment by PromoFaux** [comment]
@jacobsalmela @dschaper 

So, I'm pretty sure this fix negates the need for whitelist.sh. Take a look and let me know what you think

**Comment by dschaper** [comment]
@PromoFaux Thanks, I'll have a look and see what I can see!

**Comment by PromoFaux** [comment]
ahem.

**Comment by dschaper** [comment]
Branches are good... Branch early and often is the key to Git...

**Comment by PromoFaux** [comment]
@dschaper Whitelist.sh updated to reflect changes to gravity.sh

**Comment by PromoFaux** [comment]
Hopefully all this is good! If nothing else, I've learnt a lot about bash scripting and git tonight.

**Comment by jacobsalmela** [comment]
Wow, lots of stuff to look over!  I haven't had as much time with my new job, but I think the whitelist bug needs to be squashed first as there are two issues open about it.  After that, the other bugs will be next.

I'll do some testing tonight with what you have done and try my best to get as much done as I can tonight.

**Comment by PromoFaux** [comment]
@jacobsalmela There is a lot less there than it looks like.. just a large amount of commits because I kept thinking of other things/noticing a couple mistakes. 

In terms of squashing the whitelist bug, this removes entires for whitelisted domains in the gravity.list file for both ipv4 and ipv6.

for the blacklist it adds it before running gravity_advanced()...

as far as I can tell, if it exists in the whitelist.txt / blacklist.txt.. consider it white/blacklisted.

**Comment by jacobsalmela** [comment]
So your changes seem to work well at removing/adding both IPv4 and IPv6.  It also creates the whitelist/blacklist text files if they don't exist.  However, I was hoping to have `whitelist.sh` and `blacklist.sh` be independent of `gravity.sh`--Partially because of [this](https://github.com/jacobsalmela/AdminLTE/pull/9), but also because to allow users to quickly white or blacklist a domain without having to run `gravity.sh`: it would just remove or add the domain and then reload `dnsmasq`.  There is no need to try to download the new lists and recreate `gravity.list` from scratch each time.

So for example, in your `gravity.sh` you are using the [cool perl command](https://github.com/PromoFaux/pi-hole/blob/master/gravity.sh#L204-L205) to whitelist domains:
```
awk -F':' '{ print $1 }' $latentWhitelist | xargs -I {} perl -i -ne'print unless /[^.]'{}'(?!.)/;' $adList
```
But then in your `whitelist.sh`, a [different approach](https://github.com/PromoFaux/pi-hole/blob/master/advanced/Scripts/whitelist.sh#L28-L36) is being used:
```
grep -Ex -q "$latentPattern" $whiteList || echo $latentPattern >> $latentWhitelist
```

So as I mentioned in #139, it would be nice to outsource the whitelisting to an external script, so it would look something like this:

```
function gravity_Whitelist() {

	# Whitelist (if applicable) domains
	if [[ -r $whitelist ]];then
              sudo /usr/local/bin/whitelist.sh $(cat /etc/pihole/whitelist.txt)
        else
              echo "* Nothing to whitelist"
        fi
```
The same for the blacklist:
```
function gravity_blacklist() {

	# Blacklist (if applicable) domains
	if [[ -r $blacklist ]];then
              sudo /usr/local/bin/blacklist.sh $(cat /etc/pihole/blacklist.txt)
        else
              echo "* Nothing to blacklist"
        fi
```
This way, users can run `whitelist.sh` and `blacklist.sh` at any time if they find a domain they want to apply.  This will also make the code more modular and easier to manage.  It also will help with the Web UI whitelist/blacklist pages that I linked to earlier.

If you are up for it, try to make those changes.  If not, we can definitely use chunks of what you have done.

I hope what I am saying makes sense.  Let me know your thoughts.

**Comment by PromoFaux** [comment]
Makes sense, I can take a look tomorrow.

To explain my thinking however...
gravity.sh runs at midnight on a cron job, right? So it needs to load the whitelists anyway. It makes no sense for it to outsource to external scripts that reload the dnsmasq at this point as the master list hasn't been completed yet.

All that white/blacklist.sh do is add the domains to the existing white/latentwhite/blacklist.txt and then rerun gravity.sh. It also means that next time gravity.sh runs, the domains are re-included. The different approach is used in whitelist.sh because it doesn't need the regex required by gravity.sh to actually remove them from gravity.list, it just adds it to whitelist.txt as the user typed it, and to latentwhitelist.txt with the periods escaped. To be fair, latentwhitelist.txt could probably be scrapped.

If you like, I can change the two scripts to just change the hosts file and reload dnsmasq instead of running gravity.sh to do the same job? 

If the jobs are outsourced, then the dnsmasq is reloaded an unnecessary amount of times

**Comment by jacobsalmela** [comment]
Hmmm.  Let me think it over some more.

**Comment by Mcat12** [comment]
As I see it, the reasons we have whitelist.sh and now blacklist.sh are:

1. Users can easily add to the lists without waiting for gravity
2. The in-the-works white/blacklist [site](https://github.com/jacobsalmela/AdminLTE/pull/9) can quickly add (and hopefully subtract) to/from the lists.

Regarding the last part, it would be helpful to have the ability to take off items from the white/blacklist from these scripts.

**Comment by PromoFaux** [comment]
@Mcat12 That makes sense.I'll take a look later on today and see what I come up with. What I'll probably end up doing is branching an submitting as a fresh pull..

**Pull request closed without merging**
