### PR TITLE
Cherry pick from PR73

### PR DESCRIPTION
**Pull request by dschaper**
Cherry picked commits from #73, the two problem commits are 5d66f0e and a6a114a. Both are commits to gravity.sh. I'll take a look at them and see what is conflicting, but in the mean time the install script commits are good to go.

### CODE REVIEW

**Comment by dschaper** [comment]
5d66f0e looks like it re-introduced a bunch of code from the old swap file process. I'll try to fix that up...

**Comment by jacobsalmela** [comment]
Well at least someone knows what they are doing (and it isn't me!)

**Comment by dschaper** [comment]
Just make sure you double check what I did, I might not know as much as you think I do!

**Comment by jacobsalmela** [comment]
I just tested it a few times and it seemed to work as expected.

**Comment by dschaper** [comment]
Good, what's next?

**Comment by jacobsalmela** [comment]
Now that the installer is prettier and more adaptive.  My focus is on the Web interface (adding whitelist editor, advanced stats, domain finder, etc.)  

I would also like to parse down the ABP EasyLists to get the domains (but it might be worthwhile to check if these have domains that we already have.

**Comment by dschaper** [comment]
Okay, I'll take a go at the packaging then, get this into a deb that can be pulled via apt-get. (And try to port this over to FreeBSD, I'm running that on the gateway/VPN Pi...)

**Comment by DonLexos** [comment]
I checked the new files, the new cron seems to mention a file that is not there yet (to collect the daily stats). I am aware the admin interface will not show them but right now only the new daily purge script is there.

**Comment by dschaper** [comment]
Hope I'm not barging in and taking over things, that's not what I meant to do...

**Comment by jacobsalmela** [comment]
I appreciate any help that is offered, so no worries.  

@DonLexos You found my hint!  The script isn't done yet, but eventually, it will update the Web interface with historical stats.  I just put in there now for testing it on my end.
screen shot 2015-11-15 at 16 01 59

**Comment by DonLexos** [comment]
Ah ok, since I wanted to merge some of the changes in (and not do a full reinstall from scratch) I checked the differences. I do your daily cleanup by hand once a week or so (not that much traffic) but noticed that extra line in the new cron file ;-)
New admin looks good! Can't wait :+1:

**Comment by meliton** [comment]
I'm wondering if the web interface can be used to configure the Pi-hole.

**Comment by jacobsalmela** [comment]
Not yet, but it's in the works!

**Comment by dschaper** [comment]
Thanks for understanding! I'm more than happy to help out in any way I can...

**Pull request merged**
