### PR TITLE
Fix merge conflicts

### PR DESCRIPTION
**Pull request by dschaper**

### CODE REVIEW

**Comment by jacobsalmela** [comment]
You are a `git`guru.

**Comment by dschaper** [comment]
Lol, fixes multiple issues. I'll tag them here...

**Comment by dschaper** [comment]
Fixes #112, #113, #114.

**Comment by jacobsalmela** [comment]
Oh yep, I was just going to ask that.

**Comment by jacobsalmela** [comment]
Cool.  Now that the bugs are fixed, we can work on enhancements, which are a lot more fun! 🙃

**Comment by dschaper** [comment]
Lol, yeah, I have some more stuff that should be ready later on tonight...

**Comment by dschaper** [comment]
Check on this just to make sure, but I just ran through with 4 IPs assigned to the interface and added a 5th and all seems to be good with the 5th IP being assigned to `gravity.list`. And it's using the code to pull on Raspbian/Debian/Ubuntu. Thanks to @ricardo77 for the time on his VPS.

**Pull request merged**
